apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: gcr.io/gvgamers/express:latest
        ports:
        - containerPort: 3000
        env:
        - name: 
