name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE: express-app
  DEPLOYMENT_NAME: express-deployment
  ZONE: us-east1-b
  CLUSTER_NAME: temp-cluster

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Install gke-cloud-auth-plugin
      run: |
        echo "deb http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project ${{ secrets.PROJECT_ID }}
        
    # Build the Docker image
    - name: Build
      run: |
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Install kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    # Deploy the Docker image to the GKE cluster changing things
    - name: Deploy
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME auth=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA --record
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide